/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Dialog;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import kontroleri.MestoKontroler;
import kontroleri.OsobaKreirajKontroler;
import model.Drzava;
import model.FormaMod;
import model.Mesto;

/**
 *
 * @author vuk
 */
public class MestoKreirajForma extends javax.swing.JDialog {

    private MestoKontroler roditeljMesto;
    private OsobaKreirajKontroler roditeljOsoba;
    private Mesto selektovano;
    private FormaMod mod;
    /**
     * Creates new form MestoKreirajForma
     * @param parent
     * @param modal
     */
    public MestoKreirajForma(java.awt.Frame parent,Dialog parentDialog, boolean modal, MestoKontroler roditeljMesto,
            OsobaKreirajKontroler roditeljOsoba, Mesto selektovano, FormaMod mod) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.roditeljMesto=roditeljMesto;
        this.roditeljOsoba=roditeljOsoba;
        this.selektovano=selektovano;
        this.mod=mod;
    }

    public Mesto getSelektovano() {
        return selektovano;
    }

    public FormaMod getMod() {
        return mod;
    }


    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }


    public JButton getjButtonUnesi() {
        return jButtonUnesi;
    }

    public JComboBox<Drzava> getjComboBoxDrzava() {
        return jComboBoxDrzava;
    }

    public JTextField getjTextFieldNaziv() {
        return jTextFieldNaziv;
    }

    public MestoKontroler getRoditeljMesto() {
        return roditeljMesto;
    }

    public OsobaKreirajKontroler getRoditeljOsoba() {
        return roditeljOsoba;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jComboBoxDrzava = new javax.swing.JComboBox<>();
        jButtonUnesi = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv:");

        jLabel2.setText("Država:");

        jButtonUnesi.setText("Unesi");

        jButtonOdustani.setText("Odustani");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButtonUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jButtonOdustani))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNaziv)
                            .addComponent(jComboBoxDrzava, 0, 177, Short.MAX_VALUE))))
                .addGap(49, 85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonUnesi))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonUnesi;
    private javax.swing.JComboBox<Drzava> jComboBoxDrzava;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldNaziv;
    // End of variables declaration//GEN-END:variables

    public void kreirajAddActionListener(ActionListener actionListener) {
        jButtonUnesi.addActionListener(actionListener);
    }

    public void odustaniAddActionListener(ActionListener actionListener) {
        jButtonOdustani.addActionListener(actionListener);
    }
}
