/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import kontroleri.SobaKontroler;
import model.FormaMod;
import model.Soba;
import model.TipSobe;

/**
 *
 * @author vuk
 */
public class SobaKreirajForma extends javax.swing.JDialog {

    private SobaKontroler roditelj;
    private Soba selektovana;
    private FormaMod mod;
    /**
     * Creates new form SobaKreirajForma
     */
    public SobaKreirajForma(java.awt.Frame parent, boolean modal, SobaKontroler roditelj, Soba selektovana, FormaMod mod) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.roditelj=roditelj;
        this.selektovana=selektovana;
        this.mod=mod;
    }

    public SobaKontroler getRoditelj() {
        return roditelj;
    }

    public Soba getSelektovana() {
        return selektovana;
    }

    public FormaMod getMod() {
        return mod;
    }

    public JButton getjButtonOdustani() {
        return jButtonOdustani;
    }

    public JButton getjButtonUnesi() {
        return jButtonUnesi;
    }

    public JComboBox<TipSobe> getjComboBoxTipSobe() {
        return jComboBoxTipSobe;
    }

    public JTextField getjTextFieldCena() {
        return jTextFieldCena;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonUnesi = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCena = new javax.swing.JTextField();
        jComboBoxTipSobe = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonUnesi.setText("Unesi");

        jButtonOdustani.setText("Odustani");

        jLabel1.setText("Cena noćenja:");

        jLabel2.setText("Tip sobe:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonUnesi, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(jButtonOdustani))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCena)
                            .addComponent(jComboBoxTipSobe, 0, 144, Short.MAX_VALUE))))
                .addGap(0, 117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxTipSobe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOdustani)
                    .addComponent(jButtonUnesi))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JButton jButtonUnesi;
    private javax.swing.JComboBox<TipSobe> jComboBoxTipSobe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldCena;
    // End of variables declaration//GEN-END:variables

    public void kreirajAddActionListener(ActionListener actionListener) {
        jButtonUnesi.addActionListener(actionListener);
    }

    public void odustaniAddActionListener(ActionListener actionListener) {
        jButtonOdustani.addActionListener(actionListener);
    }


}
